version: '3.3'
networks:
  chatgpt-customer-service-chat:
services:
  backend:
    logging:
      driver: json-file
      options:
        max-size: "200k" # Maximum log file size
        max-file: "10"
    restart: always
    build:
      dockerfile: Dockerfile
      context: backend
    networks:
      - chatgpt-customer-service-chat
    ports:
      - "3307:${API_PUBLIC_PORT}"
    env_file:
      - .env
    volumes:
      - ./backend/:/app
  redis:
    image: "redis/redis-stack:6.2.6-v10"
    restart: always
    networks:
      - chatgpt-customer-service-chat
    # uncomment these lines if you want to expose redis
    # ports:
    #  - "6379:6379"
  # uncomment this if you already have a mysql server running
  mysql:
    image: "mysql:5.7.44"
    restart: always
    networks:
      - chatgpt-customer-service-chat
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    # uncomment these lines if you want to expose mysql server
    # ports:
    #   - "3306:3306"
    # the mysql_shared folder is a tool to share .sql files into the container and be able to import them in mysql
    volumes:
      - ./mysql-shared:/mysql-shared
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
