version: '3.3'
networks:
  chatgpt-customer-service-chat:
services:
  backend:
    logging:
      driver: json-file
      options:
        max-size: "200k" # Maximum log file size
        max-file: "10"
    restart: always
    build:
      dockerfile: Dockerfile
      context: backend
    networks:
      - chatgpt-customer-service-chat
    ports:
      - "3307:${API_PUBLIC_PORT}"
    env_file:
      - .env
    volumes:
      - ./backend/:/app
  redis:
    image: "redis/redis-stack:6.2.6-v10"
  # uncomment this if you already have a mysql
  mysql:
    image: "mysql:5.7.44"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
